# Generated by Django 3.1.5 on 2021-01-25 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SystemLogin', '0002_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='personal'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='administrador'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255, verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='apodo'),
        ),
    ]
